# theme: jekyll-theme-minimal
# theme: jekyll-theme-cayman

# gems:
#   - jekyll-pdf

# defaults:
#   -
#     source: ""

markdown: kramdown
kramdown:
    math_engine: mathjax
    parse_block_html: true